### PR TITLE
add --skip-aliases to skip lambdas with an alias attached

### PR DESCRIPTION
**Pull request by tricia-wf**
PR title sums it up, but please let me know any thoughts you have!

### CODE REVIEW

**Comment by karl-cardenas-coding** [comment]
Hi @tricia-wf thanks for the PR. I'll try to sneak in sometime before Sunday to review the code and provide feedback. One item that stands out  right off the bat is that the README needs to get updated to reflect this new capability 🙂

**Comment by tricia-wf** [comment]
Hi, @karl-cardenas-coding - ping on this? No rush, currently we're running my branch of this, but it'd be great to get the change merged in so we can go back to using your repo.

**Comment by karl-cardenas-coding** [comment]
Hi @tricia-wf I'll take a peek tonight. Sorry, just been busy with work these past few weeks.

**Comment by karl-cardenas-coding** [comment]
Merging into #91 to add dependency updates.

**Comment by tricia-wf** [comment]
Thank you!

**Pull request merged**
